version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: django
      POSTGRES_PASSWORD: your_password
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"  

  web:
    image: hmzahkml/atypon-fnal:latest
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
  
  front:
      build: ./src
      ports:
      - "3000:3000"
      volumes:
      - ./src:/src

volumes:
  postgres_data:
